[package]
name = "automat"
version = "0.0.2"
authors = ["Ömür Özkir <oemuer.oezkir@gmail.com>"]
edition = "2018"
description = "Data wrangling from the command line"
license = "Unlicense/MIT"

[[bin]]
name = "atm"
path = "src/main.rs"

[dependencies]
structopt = "0.3.13"

[dev-dependencies]
assert_cmd = "0.10"
predicates = "1"
tempfile = "3"
